//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUnitTest1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUnitTest1.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во конфликтов: .
        /// </summary>
        internal static string msg_count_conflicts {
            get {
                return ResourceManager.GetString("msg_count_conflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалено акций: .
        /// </summary>
        internal static string msg_count_delete_promotions {
            get {
                return ResourceManager.GetString("msg_count_delete_promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во акций: .
        /// </summary>
        internal static string msg_count_promotions {
            get {
                return ResourceManager.GetString("msg_count_promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус акции не изменён.
        /// </summary>
        internal static string msg_not_toggle {
            get {
                return ResourceManager.GetString("msg_not_toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект создан.
        /// </summary>
        internal static string msg_object_created {
            get {
                return ResourceManager.GetString("msg_object_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект удалён.
        /// </summary>
        internal static string msg_object_delete {
            get {
                return ResourceManager.GetString("msg_object_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не создан.
        /// </summary>
        internal static string msg_object_not_created {
            get {
                return ResourceManager.GetString("msg_object_not_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не удалён.
        /// </summary>
        internal static string msg_object_not_delete {
            get {
                return ResourceManager.GetString("msg_object_not_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты равны.
        /// </summary>
        internal static string msg_objects_equal {
            get {
                return ResourceManager.GetString("msg_objects_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты не равны.
        /// </summary>
        internal static string msg_objects_not_equal {
            get {
                return ResourceManager.GetString("msg_objects_not_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акция активирована.
        /// </summary>
        internal static string msg_promotion_enable {
            get {
                return ResourceManager.GetString("msg_promotion_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акция не активирована.
        /// </summary>
        internal static string msg_promotion_not_enable {
            get {
                return ResourceManager.GetString("msg_promotion_not_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акция недействительна.
        /// </summary>
        internal static string msg_promotion_not_valid {
            get {
                return ResourceManager.GetString("msg_promotion_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акция действительна.
        /// </summary>
        internal static string msg_promotion_valid {
            get {
                return ResourceManager.GetString("msg_promotion_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест провален.
        /// </summary>
        internal static string msg_test_fail {
            get {
                return ResourceManager.GetString("msg_test_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тест успешно выполнен.
        /// </summary>
        internal static string msg_test_pass {
            get {
                return ResourceManager.GetString("msg_test_pass", resourceCulture);
            }
        }
    }
}
