//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUnitTest1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUnitTest1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O8bS0aZNZbKuiONw.
        /// </summary>
        public static string api_key {
            get {
                return ResourceManager.GetString("api_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22174.
        /// </summary>
        public static string merchant_id {
            get {
                return ResourceManager.GetString("merchant_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string packages {
            get {
                return ResourceManager.GetString("packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /promotions/{0}/payment_systems.
        /// </summary>
        public static string payment_systems {
            get {
                return ResourceManager.GetString("payment_systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2682.
        /// </summary>
        public static string payment_systems_id {
            get {
                return ResourceManager.GetString("payment_systems_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /promotions/{0}/periods.
        /// </summary>
        public static string periods {
            get {
                return ResourceManager.GetString("periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15861.
        /// </summary>
        public static string project_id {
            get {
                return ResourceManager.GetString("project_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /promotions/{0}.
        /// </summary>
        public static string promotion {
            get {
                return ResourceManager.GetString("promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /promotions.
        /// </summary>
        public static string promotions {
            get {
                return ResourceManager.GetString("promotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /promotions/{0}/review.
        /// </summary>
        public static string review {
            get {
                return ResourceManager.GetString("review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /promotions/{0}/rewards.
        /// </summary>
        public static string rewards {
            get {
                return ResourceManager.GetString("rewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /promotions/{0}/subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /promotions/{0}/toggle.
        /// </summary>
        public static string toogle {
            get {
                return ResourceManager.GetString("toogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.xsolla.com/merchant/v2/merchants/{0}{1}.
        /// </summary>
        public static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
    }
}
